### ISSUE TITLE
doesnt work with windmills says (INVALID PLACEMENT) yet will still snap to the 2 active spots of it

### ISSUE THREAD

**Issue by Th1rtyS1x** [MSchmoecker/ValheimHopper#11] opened 2024-08-29 21:41 UTC
![892970_255](https://github.com/user-attachments/assets/4c7a2809-65c4-4d4c-af67-06ab70b04547)

**Comment by Th1rtyS1x** [comment] 2024-08-29 21:41
current version and know the mod works as it is able to function on kilns and furnace smelters

**Comment by Visteus** [comment] 2024-09-01 16:07
Just a note, the windmill doesn't "support" the hopper so I have to build a little "frame" to attach/support the hopper

**Comment by MSchmoecker** [comment] 2024-09-02 13:27
yes, windmills do not directly support other pieces and a frame is always needed. This is duo to the way Valheim works, a hopper behaves like a normal piece in terms of support.

However, the invalid placement may be caused by overlapping colliders. Something must have changed in between versions

**Comment by MSchmoecker** [comment] 2024-11-03 15:15
Will close this, a support structure is always needed around the hopper, the windmill alone doesn't support a hopper. It's a bit tricky, but it would be odd if this mod changed the support behaviour of windmill to support other pieces

**Closed as completed by MSchmoecker** 2024-11-03 15:15 UTC
